; KAKATA RC433 V1 - ESP32-S3 Firmware
; Platform: ESP-IDF (Arduino framework)

[env:kakata_rc433]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=0

lib_deps =
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.5
    adafruit/Adafruit MPU6050@^2.2.4
    adafruit/Adafruit BusIO@^1.14.1
    knolleary/PubSubClient@^2.8
    sui79/rc_switch@^2.2.1
